spring:
  application:
    name: cloud-storage

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update