spring:
  application:
    name: cloud-storage

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
#config de spring app se co the connect to bucket duoc tao tren aws
#bucket: noi ma se luu tru nhung file ma ta upload len
aws:
  s3:
    bucketName: cloud-storage-bucket
    accessKey: AKIATX3PICUAHKAYWG7F
    secretKey: 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
